import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    baseContainer: {
        flex: 1,
        // justifyContent: 'center',
        // alignItems: 'center',
        // justifyContent: 'center',
    },
    topContCenter:{
        // width: '100%',
        flex: 1,
        // marginTop:
        paddingVertical: 20,
        alignItems: 'center',
        justifyContent: 'center'
    },
    formContainer: {
        flex: 1,
        // paddingHorizontal: 15,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#514fe1'
    },
    input: {
        width: '85%',
        height: 50,
        borderColor: '#d5d5df',
        // borderColor: '#d5d5df',
        borderTopWidth: 1,
        borderLeftWidth: 0,
        borderBottomWidth: 1,
        borderRightWidth: 1,
        fontFamily: 'NanumGothic-Regular',
        fontSize: 16,
        borderTopLeftRadius: 0,
        borderBottomLeftRadius: 0,
        borderBottomRightRadius: 4,
        borderTopRightRadius: 4,
    },
    titleBold: {
        fontFamily: 'NanumGothic-Regular',
        fontSize: 20,
        color: '#343434',
        paddingTop: 10,
    },
    space: {
      flex: 1,
      height: 100,
    },
    titleGreyBold: {
        fontFamily: 'NanumGothic-Bold',
        fontSize: 20,
        color: '#9aa1b3',
        paddingTop: 15,
    },
    // navBtn: {
    //     width: '100%',
    //     position: 'absolute',
    //     bottom: 0,
    //     height: 55,
    //     flexDirection: 'row',
    //     // paddingHorizontal: 15,
    //     // paddingVertical: 10,
    //     backgroundColor: '#3b52d4',
    //     borderRadius: 4,
    //     marginTop: 50,
    //     justifyContent: 'center',
    //     alignItems: 'center',
    // },
    btnText: {
        fontFamily: 'NanumGothic-Bold',
        fontSize: 14,
        color: '#fff',
        marginRight: 5,
    },
    errLabel: {
        color: '#ff0d0d',
        fontSize: 14,
        marginTop: 10,
        fontFamily: 'NanumGothic-Regular',
    },
    logo: {
        width: 100,
        height: 100
    },
    row:{
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'center',
        alignItems: 'center',
        paddingBottom: 120,
    },
    flexLeft: {
        width: '15%',
        height: 50,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: '#d5d5df',
        borderTopWidth: 1,
        borderLeftWidth: 1,
        borderRightWidth: 1,
        borderBottomWidth: 1,
        // borderRightWidth: 0,
        borderTopLeftRadius: 4,
        borderBottomLeftRadius: 4,
    },
    picker:{
      width: '100%',
        height: '100%'
    },
    logoFont: {
        flex: 1,
        position: 'absolute',
        top: '25%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    logoTxt: {
        fontSize: 50,
        // marginTop: 10,
        fontFamily: 'Proxima-Nova-Bold',
        color: '#fff',
    },
    absContainer : {
        width: '100%',
        height: 250,
        position: 'absolute',
        bottom: 0,
        right: 0,
        left: 0,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
        paddingHorizontal: 15,
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
    },
    navBtn: {
        width: '45%',
        height: 55,
        // flexDirection: 'row',
        // paddingHorizontal: 15,
        // paddingVertical: 10,
        backgroundColor: '#514fe1',
        borderRadius: 4,
        marginTop: 50,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 25,
    },
})

export default styles;
